/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardProgramsSlugRouteImport } from './routes/dashboard/programs.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardProgramsSlugIndexRouteImport } from './routes/dashboard/programs.$slug.index'
import { Route as DashboardProgramsSlugSettingsRouteImport } from './routes/dashboard/programs.$slug.settings'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProgramsSlugRoute = DashboardProgramsSlugRouteImport.update({
  id: '/programs/$slug',
  path: '/programs/$slug',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProgramsSlugIndexRoute =
  DashboardProgramsSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardProgramsSlugRoute,
  } as any)
const DashboardProgramsSlugSettingsRoute =
  DashboardProgramsSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardProgramsSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/programs/$slug': typeof DashboardProgramsSlugRouteWithChildren
  '/dashboard/programs/$slug/settings': typeof DashboardProgramsSlugSettingsRoute
  '/dashboard/programs/$slug/': typeof DashboardProgramsSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/programs/$slug/settings': typeof DashboardProgramsSlugSettingsRoute
  '/dashboard/programs/$slug': typeof DashboardProgramsSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/programs/$slug': typeof DashboardProgramsSlugRouteWithChildren
  '/dashboard/programs/$slug/settings': typeof DashboardProgramsSlugSettingsRoute
  '/dashboard/programs/$slug/': typeof DashboardProgramsSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/programs/$slug'
    | '/dashboard/programs/$slug/settings'
    | '/dashboard/programs/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/api/auth/$'
    | '/dashboard/programs/$slug/settings'
    | '/dashboard/programs/$slug'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/programs/$slug'
    | '/dashboard/programs/$slug/settings'
    | '/dashboard/programs/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/programs/$slug': {
      id: '/dashboard/programs/$slug'
      path: '/programs/$slug'
      fullPath: '/dashboard/programs/$slug'
      preLoaderRoute: typeof DashboardProgramsSlugRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/programs/$slug/': {
      id: '/dashboard/programs/$slug/'
      path: '/'
      fullPath: '/dashboard/programs/$slug/'
      preLoaderRoute: typeof DashboardProgramsSlugIndexRouteImport
      parentRoute: typeof DashboardProgramsSlugRoute
    }
    '/dashboard/programs/$slug/settings': {
      id: '/dashboard/programs/$slug/settings'
      path: '/settings'
      fullPath: '/dashboard/programs/$slug/settings'
      preLoaderRoute: typeof DashboardProgramsSlugSettingsRouteImport
      parentRoute: typeof DashboardProgramsSlugRoute
    }
  }
}

interface DashboardProgramsSlugRouteChildren {
  DashboardProgramsSlugSettingsRoute: typeof DashboardProgramsSlugSettingsRoute
  DashboardProgramsSlugIndexRoute: typeof DashboardProgramsSlugIndexRoute
}

const DashboardProgramsSlugRouteChildren: DashboardProgramsSlugRouteChildren = {
  DashboardProgramsSlugSettingsRoute: DashboardProgramsSlugSettingsRoute,
  DashboardProgramsSlugIndexRoute: DashboardProgramsSlugIndexRoute,
}

const DashboardProgramsSlugRouteWithChildren =
  DashboardProgramsSlugRoute._addFileChildren(
    DashboardProgramsSlugRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardProgramsSlugRoute: typeof DashboardProgramsSlugRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardProgramsSlugRoute: DashboardProgramsSlugRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
